// Generated by scripts/generate-reader-fingerprint.mjs. Source identity is not qualification.
export const READER_BUILD_FINGERPRINT =
  "909d2680b1e03c6b9c14f1100854bf97b2527247188eb42cb653e0c499be02b6";
export const READER_SCHEMA = "ava-reader-3";
