// Generated by scripts/generate-reader-fingerprint.mjs. Source identity is not qualification.
export const READER_BUILD_FINGERPRINT =
  "d75fbeb320ba0108115a3e839433bc8a46bcaecaf0665632166de47f025a9915";
export const READER_SCHEMA = "ava-reader-3";
