// Generated by scripts/generate-reader-fingerprint.mjs. Source identity is not qualification.
export const READER_BUILD_FINGERPRINT =
  "1bcae528da3872107ead1cefebd6e6fd379ff72c6d48bc44191714a328421950";
export const READER_SCHEMA = "ava-reader-3";
