import { expect, it } from "vitest";
import { a, b, c, flushRequests } from "../jump-session-test-fixture";
import { qaFixture } from "./qa-test-fixture";
it("held navigation runs only after release and commits after measured success", async () => {
  const f = qaFixture();
  f.command("arm-hold", { stage: "navigate", target: c });
  f.session.jump(c);
  await flushRequests();
  expect(f.navigate).not.toHaveBeenCalled();
  expect(f.acks.at(-1)?.phase).toBe("held");
  f.command("release");
  await flushRequests();
  expect(f.navigate).toHaveBeenCalledExactlyOnceWith(c, 1);
  expect(f.view.state.entries).toEqual([]);
  f.qa.settle(f.intent(), true);
  await flushRequests();
  expect(f.view.state.entries).toEqual([a]);
});
it("superseded held work cannot dispatch or add history after release", async () => {
  const f = qaFixture();
  f.command("arm-hold", { stage: "navigate", target: c });
  f.session.jump(c);
  const stale = f.intent();
  await flushRequests();
  f.session.jump(b);
  await flushRequests();
  f.qa.settle(f.intent(), true);
  await flushRequests();
  f.command("release");
  await flushRequests();
  f.qa.settle(stale, true);
  await flushRequests();
  expect(f.navigate.mock.calls.map(([point]) => point)).toEqual([b]);
  expect(f.acks.some((ack) => ack.phase === "released-stale")).toBe(true);
  expect(f.view.origin).toEqual(b);
  expect(f.view.state.entries).toEqual([a]);
});
it("cancel invalidates a held request and restores origin through the real session", async () => {
  const f = qaFixture();
  f.command("arm-hold", { stage: "navigate", target: c });
  f.session.jump(c);
  const stale = f.intent();
  await flushRequests();
  f.command("cancel");
  await flushRequests();
  f.qa.settle(stale, true);
  await flushRequests();
  expect(f.view.state.pending?.rollback).toBe(true);
  expect(f.navigate.mock.calls.map(([point]) => point)).toEqual([a]);
  f.qa.settle(f.intent(), true);
  await flushRequests();
  expect(f.view.origin).toEqual(a);
  expect(f.view.state.entries).toEqual([]);
});
it("exit disposes held work without navigating a retained reader", async () => {
  const f = qaFixture();
  f.command("arm-hold", { stage: "navigate", target: c });
  f.session.jump(c);
  const stale = f.intent();
  await flushRequests();
  f.session.dispose();
  f.disconnect();
  await flushRequests();
  f.session.activate();
  f.qa.settle(stale, true);
  await flushRequests();
  expect(f.navigate).not.toHaveBeenCalled();
  expect(f.view.state.entries).toEqual([]);
});
