"""Printer labels need complete native marginal evidence, not arbitrary page mentions."""

import unittest

from ava_pdf_epub.contracts.profiles import BILINGUAL_PROFILE, LEGACY_PROFILE
from ava_pdf_epub.reconstruction_v2.furniture import furniture_ids
from ava_pdf_epub.reconstruction_v2.printer_folios import printer_folio_labels


class PrinterFolioEvidenceTests(unittest.TestCase):
    def page(self):
        # Real source observations are generated by the independent PDF extraction below.
        from .test_pdf_links import observation

        page = observation()
        from ava_pdf_epub.reconstruction_v2.observations import Glyph, NativeLine

        box = dict(coordinate_space="page_points_top_left", x0=10, y0=94, x1=90, y1=99)
        line = NativeLine(
            id="printer",
            box=box,
            text="North Press print page iv",
            glyphs=[
                Glyph(text="North Press print page iv", box=box, font="Serif", size=5, visible=True)
            ],
            style=dict(id="printer", family="serif"),
        )
        return page.model_copy(update={"lines": [*page.lines, line], "risks": []})

    def test_only_current_profile_adds_a_complete_single_printer_label(self):
        page = self.page()
        self.assertEqual({"printer": "iv"}, printer_folio_labels(page))
        self.assertIn("printer", furniture_ids([page], BILINGUAL_PROFILE))
        self.assertNotIn("printer", furniture_ids([page], LEGACY_PROFILE))

    def test_interior_heading_reference_and_incomplete_source_proof_stay_unknown(self):
        page = self.page()
        line = page.lines[-1]
        for change in [
            {"box": line.box.model_copy(update={"y0": 60, "y1": 65})},
            {"glyphs": [line.glyphs[0].model_copy(update={"size": 50})]},
            {"text": "See print page iv"},
            {"glyphs": [line.glyphs[0].model_copy(update={"visible": False})]},
            {"glyphs": [line.glyphs[0].model_copy(update={"font": ""})]},
            {"glyphs": [line.glyphs[0].model_copy(update={"text": "partial"})]},
        ]:
            with self.subTest(change=change):
                value = page.model_copy(
                    update={"lines": [*page.lines[:-1], line.model_copy(update=change)]}
                )
                self.assertEqual({}, printer_folio_labels(value))
        self.assertEqual({}, printer_folio_labels(page.model_copy(update={"risks": ["uncertain"]})))
        self.assertEqual(
            {}, printer_folio_labels(page.model_copy(update={"lines": [*page.lines, line]}))
        )
